// js/cars.js
const cars = [
  {
    id: 1,
    name: "Lamborghini Aventador",
    brand: "Lamborghini",
    maker: "Automobili Lamborghini S.p.A.",
    country: "Italy",
    price: "$500,000",
    speed: "350 km/h",
    hp: "770 hp",
    zeroTo100Mph: "5.9 s",
    weight: "1,575 kg",
    vehicleType: "Combustion",
    description: "A flagship V12 supercar famous for its aggressive, stealth-fighter styling and iconic scissor doors.",
    images: [
      "https://preview.thenewsmarket.com/Previews/lamb/StillAssets/1920x1440/518305.jpg",
      "https://www.kimballstock.com/pix/car/p/06/lam-01-rk0798-01p.jpg",
      "https://preview.thenewsmarket.com/Previews/lamb/StillAssets/1920x1440/518294.jpg"
    ],
  },
  {
    id: 2,
    name: "Ferrari 488",
    brand: "Ferrari",
    maker: "Ferrari S.p.A.",
    country: "Italy",
    price: "$280,000",
    speed: "330 km/h",
    hp: "661 hp",
    zeroTo100Mph: "6.9 s",
    weight: "1,475 kg",
    vehicleType: "Combustion",
    description: "An incredibly responsive mid-engine V8 supercar that delivers blistering track performance and daily usability.",
    images: [
      "https://www.kimballstock.com/pix/car/p/06/frr-04-rk0736-01p.jpg",
      "https://www.kimballstock.com/pix/car/p/06/frr-04-rk0722-01p.jpg",
      "https://autodesignmagazine.com/wp-content/uploads/2016/01/2015091501_Ferrari-488GTB.jpg"
    ],
  },
  {
    id: 3,
    name: "McLaren 720S",
    brand: "McLaren",
    maker: "McLaren Automotive",
    country: "United Kingdom",
    price: "$300,000",
    speed: "341 km/h",
    hp: "710 hp",
    zeroTo100Mph: "4.8 s",
    weight: "1,419 kg",
    vehicleType: "Combustion",
    description: "A lightweight, aerodynamically advanced supercar offering mind-bending acceleration and a high-tech carbon fiber chassis.",
    images: [
      "https://hips.hearstapps.com/autoweek/assets/s3fs-public/7506-mclaren720s-07-studio.jpg",
      "https://hips.hearstapps.com/autoweek/assets/s3fs-public/7508-mclaren720s-09-studio.jpg",
      "https://hips.hearstapps.com/autoweek/assets/s3fs-public/7523-mclaren720s-24-studio.jpg"
    ],
  },
  {
    id: 4,
    name: "Bugatti Chiron",
    brand: "Bugatti",
    maker: "Bugatti Automobiles S.A.S.",
    country: "France",
    price: "$3,000,000",
    speed: "420 km/h",
    hp: "1500 hp",
    zeroTo100Mph: "4.4 s",
    weight: "1,995 kg",
    vehicleType: "Combustion",
    description: "An ultra-luxury hypercar powered by a quad-turbo W16 engine, renowned for its record-breaking top speeds.",
    images: [
      "https://www.kimballstock.com/pix/car/p/01/aut-02-rk0165-01p.jpg",
      "https://picolio.auto123.com/auto123tv/images/xc/ri/BUgatti-Chiron_003.JPG?scaledown=980",
      "https://privacy-proxy-server.usercentrics.eu/video/youtube/EX0AIOfKRBg-poster-image"
    ],
  },
  {
    id: 5,
    name: "Porsche 911 Turbo S",
    brand: "Porsche",
    maker: "Porsche AG",
    country: "Germany",
    price: "$230,000",
    speed: "330 km/h",
    hp: "640 hp",
    zeroTo100Mph: "5.8 s",
    weight: "1,640 kg",
    vehicleType: "Combustion",
    description: "The ultimate everyday supercar, combining all-wheel-drive traction with explosive twin-turbo flat-six power.",
    images: [
      "https://newsroom.porsche.com/.imaging/mte/porsche-templating-theme/image_1290x726/dam/US-local/Press-Releases/2025/9-SEPTEMBER/New-911-Turbo-S/Images/Coupe/PCNA25_1117_fine.jpg/jcr:content/PCNA25_1117_fine.jpg",
      "https://press.porsche.com/prod/presse_pag/PressResources.nsf/jumppage/modelle-911-911_turbo_s/$file/2020_911_turbo_s.jpg",
      "https://cdn.dealeraccelerate.com/studio/1/28/3274/x/2019-porsche-911-turbo-s"
    ],
  },
  {
    id: 6,
    name: "Audi R8 V10 Plus",
    brand: "Audi",
    maker: "Audi Sport GmbH",
    country: "Germany",
    price: "$200,000",
    speed: "330 km/h",
    hp: "602 hp",
    zeroTo100Mph: "7.6 s",
    weight: "1,555 kg",
    vehicleType: "Combustion",
    description: "A refined, naturally aspirated V10 supercar sharing its core DNA with the Lamborghini Huracán.",
    images: [
      "https://www.netcarshow.com/Audi-R8_V10_plus-2013-Front_Three-Quarter.dda750a0.jpg",
      "https://www.netcarshow.com/Audi-R8_Coupe_V10_plus_selection_24h-2016-Rear.cc3a1530.jpg",
      "https://www.netcarshow.com/Audi-R8_V10_plus-2013-Side_Profile.dda750a0.jpg"
    ],
  },
  {
    id: 7,
    name: "Mercedes-AMG GT Black Series",
    brand: "Mercedes-Benz",
    maker: "Mercedes-AMG GmbH",
    country: "Germany",
    price: "$325,000",
    speed: "325 km/h",
    hp: "720 hp",
    zeroTo100Mph: "6.8 s",
    weight: "1,615 kg",
    vehicleType: "Combustion",
    description: "A track-focused monster featuring a flat-plane crank V8 and extreme aerodynamics derived from GT3 racing.",
    images: [
      "https://www.netcarshow.com/Mercedes-Benz-AMG_GT_Black_Series-2021-Front.395da237.jpg",
      "https://www.netcarshow.com/Mercedes-Benz-AMG_GT_Black_Series-2021-Rear_Three-Quarter.395da237.jpg",
      "https://www.netcarshow.com/Mercedes-Benz-AMG_GT_Black_Series-2021-Side_Profile.395da237.jpg"
    ],
  },
  {
    id: 8,
    name: "BMW M8 Competition",
    brand: "BMW",
    maker: "BMW M GmbH",
    country: "Germany",
    price: "$130,000",
    speed: "305 km/h",
    hp: "617 hp",
    zeroTo100Mph: "7.2 s",
    weight: "1,885 kg",
    vehicleType: "Combustion",
    description: "A heavily muscular grand tourer that crosses into supercar territory with its ferocious twin-turbo V8 and all-wheel drive.",
    images: [
      "https://www.netcarshow.com/BMW-M8_Competition_Coupe-2020-Front.0616f34d.jpg",
      "https://mediacloud.carbuyer.co.uk/image/private/s--y-iJbnqW--/f_auto,t_content-image-full-mobile@1/v1579647100/carbuyer/2019/06/p90348780_highres.jpg",
      "https://mediapool.bmwgroup.com/cache/P9/201905/P90348774/P90348774-the-all-new-bmw-m8-competition-coupe-06-2019-600px.jpg"
    ],
  },
  {
    id: 9,
    name: "Aston Martin DBS Superleggera",
    brand: "Aston Martin",
    maker: "Aston Martin Lagonda",
    country: "United Kingdom",
    price: "$316,000",
    speed: "340 km/h",
    hp: "715 hp",
    zeroTo100Mph: "6.4 s",
    weight: "1,693 kg",
    vehicleType: "Combustion",
    description: "A stunningly beautiful V12 grand tourer offering massive torque and classic British elegance.",
    images: [
      "https://www.dimmitt.com/blogs/3093/wp-content/uploads/2018/07/aston-martin-DBS-Superleggera-tampa-dimmitt-front.jpg",
      "https://c8.alamy.com/comp/T19AN6/2019-aston-martin-dbs-superleggera-rear-34-view-wales-uk-T19AN6.jpg",
      "https://www.topgear.com/sites/default/files/images/news-article/carousel/2018/06/67314f1aeebb1417f399a92ac973c81d/dbs_superleggera_11.jpg"
    ],
  },
  {
    id: 10,
    name: "Pagani Huayra",
    brand: "Pagani",
    maker: "Pagani Automobili S.p.A.",
    country: "Italy",
    price: "$2,600,000",
    speed: "383 km/h",
    hp: "730 hp",
    zeroTo100Mph: "5.6 s",
    weight: "1,350 kg",
    vehicleType: "Combustion",
    description: "A rolling piece of art featuring active aerodynamics and a bespoke AMG-sourced twin-turbo V12.",
    images: [
      "https://www.kimballstock.com/pix/car/p/01/aut-09-rk1348-01p.jpg",
      "https://www.pagani.com/app/uploads/2025/02/4-Huayra-R-Evo-Roadster_Rear.jpg",
      "https://www.pagani.com/app/uploads/2025/02/2-Huayra-R-Evo-Roadster_Side.jpg"
    ],
  },
  {
    id: 11,
    name: "Koenigsegg Jesko",
    brand: "Koenigsegg",
    maker: "Koenigsegg Automotive AB",
    country: "Sweden",
    price: "$3,000,000",
    speed: "480 km/h",
    hp: "1600 hp",
    zeroTo100Mph: "4.7 s",
    weight: "1,420 kg",
    vehicleType: "Combustion",
    description: "A track-oriented megacar engineered to break the 300 mph barrier, featuring a revolutionary 9-speed 'Light Speed Transmission'.",
    images: [
      "https://www.kimballstock.com/pix/car/p/06/aut-55-rk0017-01p.jpg",
      "https://hips.hearstapps.com/hmg-prod/images/koenigsegg-jesko-105-1551799593.jpg",
      "https://mb.cision.com/Public/18511/2881595/8c16995c0fb16b3a_org.jpg"
    ],
  },
  {
    id: 12,
    name: "Ford GT",
    brand: "Ford",
    maker: "Ford Motor Company / Multimatic",
    country: "USA / Canada",
    price: "$500,000",
    speed: "347 km/h",
    hp: "660 hp",
    zeroTo100Mph: "6.4 s",
    weight: "1,385 kg",
    vehicleType: "Combustion",
    description: "A Le Mans-winning race car for the road, built almost entirely of carbon fiber with a potent EcoBoost V6.",
    images: [
      "https://www.netcarshow.com/Ford-GT-2017-Front.973f35eb.jpg",
      "https://www.automotiverhythms.com/wp-content/uploads/2022/02/2022-Ford-GT-Alan-Mann-Heritage-Edition_05.jpg",
      "https://fordauthority.com/wp-content/uploads/2020/08/2021-Ford-GT-Studio-Series-Exterior-004-side-profile-gray-with-bronze-accents.jpg"
    ],
  },
  {
    id: 13,
    name: "Chevrolet Corvette Z06",
    brand: "Chevrolet",
    maker: "General Motors",
    country: "USA",
    price: "$110,000",
    speed: "313 km/h",
    hp: "670 hp",
    zeroTo100Mph: "6.0 s",
    weight: "1,561 kg",
    vehicleType: "Combustion",
    description: "An American supercar disruptor packing a high-revving, flat-plane crank naturally aspirated V8.",
    images: [
      "https://www.kimballstock.com/pix/car/p/07/vet-01-bk0056-01p.jpg",
      "https://news.chevroletarabia.com/dld/content/dam/Media/images/US/Vehicles/Chevrolet/Cars/Corvette_Z06/2023/Product/Vehicle/2023-chevrolet-corvette-z06-203.jpg",
      "https://www.corvetteblogger.com/images/content/uploads/2021/10/100421_9.jpg"
    ],
  },
  {
    id: 14,
    name: "Nissan GT-R Nismo",
    brand: "Nissan",
    maker: "Nissan Motor Co., Ltd.",
    country: "Japan",
    price: "$210,000",
    speed: "330 km/h",
    hp: "600 hp",
    zeroTo100Mph: "6.5 s",
    weight: "1,720 kg",
    vehicleType: "Combustion",
    description: "The pinnacle of the 'Godzilla' lineage, featuring GT3 race-derived turbochargers and carbon fiber bodywork.",
    images: [
      "https://wieck-nissanao-production.s3.us-west-1.amazonaws.com/releaseInlineImages/a5c21ac282c8cec160193ee5f450fe8a911959cb",
      "https://images.caricos.com/n/nissan/2020_nissan_gt-r_nismo/images/2560x1440/2020_nissan_gt-r_nismo_22_2560x1440.jpg",
      "https://www.thespeedjournal.com/wp-content/uploads/2019/04/2020-nissan-gt-r-nismo-3.jpg"
    ],
  },
  {
    id: 15,
    name: "Acura NSX Type S",
    brand: "Acura",
    maker: "Honda Motor Company",
    country: "USA (Assembled)",
    price: "$170,000",
    speed: "307 km/h",
    hp: "600 hp",
    zeroTo100Mph: "6.2 s",
    weight: "1,725 kg",
    vehicleType: "Hybrid",
    description: "A highly advanced hybrid supercar utilizing three electric motors and a twin-turbo V6 for precise torque vectoring.",
    images: [
      "https://wieck-honda-production.s3.us-west-1.amazonaws.com/releaseInlineImages/1bfea2109e3f1463bce8984cf31384d13fd121e9",
      "https://hips.hearstapps.com/hmg-prod/images/2022-acura-nsx-type-s-5-1628792635.jpg?crop=1xw:0.84375xh;center,top&resize=1200:*",
      "https://www.motorcarclassics.com/galleria_images/1075/1075_p24_l.jpg"
    ],
  },
  {
    id: 16,
    name: "Lexus LFA",
    brand: "Lexus",
    maker: "Toyota Motor Corporation",
    country: "Japan",
    price: "$375,000",
    speed: "325 km/h",
    hp: "552 hp",
    zeroTo100Mph: "7.6 s",
    weight: "1,480 kg",
    vehicleType: "Combustion",
    description: "A legendary, limited-production supercar famous for having one of the best-sounding V10 engines in automotive history.",
    images: [
      "https://www.kimballstock.com/pix/car/p/01/aut-09-rk1187-01p.jpg",
      "https://s.yimg.com/ny/api/res/1.2/6g_s0xGGm6f5rEeIKWHI1A--/YXBwaWQ9aGlnaGxhbmRlcjt3PTY0MDtoPTM2MA--/https://media.zenfs.com/en/car_and_driver_581/668ce12bcc8e6a0feb47de0487722766",
      "https://d2j6dbq0eux0bg.cloudfront.net/images/69857544/3911373703.jpg"
    ],
  },
  {
    id: 17,
    name: "Maserati MC20",
    brand: "Maserati",
    maker: "Maserati S.p.A.",
    country: "Italy",
    price: "$210,000",
    speed: "325 km/h",
    hp: "621 hp",
    zeroTo100Mph: "5.9 s",
    weight: "1,500 kg",
    vehicleType: "Combustion",
    description: "Maserati’s return to mid-engine supercars, powered by the innovative twin-spark 'Nettuno' V6 engine.",
    images: [
      "https://www.kimballstock.com/pix/car/p/07/aut-57-rk0002-01p.jpg",
      "https://car-images.bauersecure.com/wp-images/4158/480x270/mc20_058.jpg",
      "https://car-images.bauersecure.com/wp-images/4158/480x270/mc20_060.jpg"
    ],
  },
  {
    id: 18,
    name: "Ferrari F8 Tributo",
    brand: "Ferrari",
    maker: "Ferrari S.p.A.",
    country: "Italy",
    price: "$280,000",
    speed: "340 km/h",
    hp: "710 hp",
    zeroTo100Mph: "5.8 s",
    weight: "1,435 kg",
    vehicleType: "Combustion",
    description: "A tribute to Ferrari's most powerful V8 engine, wrapping staggering performance in beautiful, aerodynamic bodywork.",
    images: [
      "https://hips.hearstapps.com/mtg-prod/65c7fe20def97800082b12ed/ferrari-f8-tributo-front-three-quarters.jpg",
      "https://hips.hearstapps.com/mtg-prod/65c7fe2058b907000853e329/ferrari-f8-tributo-rear-three-quarters.jpg",
      "https://www.netcarshow.com/Ferrari-F8_Tributo-2020-Side_Profile.b8f33097.jpg"
    ],
  },
  {
    id: 19,
    name: "Lamborghini Huracán Performante",
    brand: "Lamborghini",
    maker: "Automobili Lamborghini S.p.A.",
    country: "Italy",
    price: "$275,000",
    speed: "325 km/h",
    hp: "631 hp",
    zeroTo100Mph: "5.9 s",
    weight: "1,382 kg",
    vehicleType: "Combustion",
    description: "A track-focused variant of the Huracán featuring the innovative 'ALA' active aerodynamics system.",
    images: [
      "https://www.kimballstock.com/pix/car/p/07/lam-01-rk0982-01p.jpg",
      "https://www.netcarshow.com/Lamborghini-Huracan_Performante-2018-Rear.3ce24414.jpg",
      "https://www.netcarshow.com/Lamborghini-Huracan_Performante-2018-Side_Profile.3ce24414.jpg"
    ],
  },
  {
    id: 20,
    name: "McLaren Senna",
    brand: "McLaren",
    maker: "McLaren Automotive",
    country: "United Kingdom",
    price: "$1,000,000",
    speed: "335 km/h",
    hp: "789 hp",
    zeroTo100Mph: "4.8 s",
    weight: "1,198 kg",
    vehicleType: "Combustion",
    description: "An unapologetic track car designed solely to set lap records, prioritizing downforce and weight reduction above all else.",
    images: [
      "https://www.kimballstock.com/pix/car/p/04/aut-28-rk0245-01p.jpg",
      "https://www.netcarshow.com/McLaren-Senna-2019-Rear_Three-Quarter.8f50278b.jpg",
      "https://www.netcarshow.com/McLaren-Senna-2019-1280-c73de03d86e1d2456fd55056f2a8c96c5c.jpg"
    ],
  },
  {
    id: 21,
    name: "Bugatti Veyron Super Sport",
    brand: "Bugatti",
    maker: "Bugatti Automobiles S.A.S.",
    country: "France",
    price: "$2,500,000",
    speed: "431 km/h",
    hp: "1200 hp",
    zeroTo100Mph: "4.8 s",
    weight: "1,838 kg",
    vehicleType: "Combustion",
    description: "The hypercar that defined an era, holding the production car top speed record for years with its massive W16 engine.",
    images: [
      "https://www.shutterstock.com/image-photo/dorlisheim-france-septembre-13th-2025-600nw-2680197625.jpg",
      "https://bugatti-newsroom.imgix.net/1aea0a52-c9e3-41d6-a718-38542fd55361/studio_004_1",
      "https://mycarheaven.com/wp-content/smush-webp/2010/08/Bugatti-Veyron-16_4-Super-Sport-side-view.jpg.webp"
    ],
  },
  {
    id: 22,
    name: "Porsche 918 Spyder",
    brand: "Porsche",
    maker: "Porsche AG",
    country: "Germany",
    price: "$845,000",
    speed: "345 km/h",
    hp: "887 hp",
    zeroTo100Mph: "4.9 s",
    weight: "1,634 kg",
    vehicleType: "Hybrid",
    description: "A member of the 'Holy Trinity', this hybrid hypercar proved that electrification could push track performance to new limits.",
    images: [
      "https://www.kimballstock.com/pix/car/p/07/por-04-bk0019-01p.jpg",
      "https://www.kimballstock.com/pix/car/p/07/por-04-bk0021-01p.jpg",
      "https://porschepictures.flowcenter.de/pmdb/thumbnail.cgi?id=271487&w=700&h=467&crop=0&public=1&cs=ddbf1637b82a79b3"
    ],
  },
  {
    id: 23,
    name: "Ferrari LaFerrari",
    brand: "Ferrari",
    maker: "Ferrari S.p.A.",
    country: "Italy",
    price: "$1,400,000",
    speed: "350 km/h",
    hp: "950 hp",
    zeroTo100Mph: "4.8 s",
    weight: "1,585 kg",
    vehicleType: "Hybrid",
    description: "Ferrari's ultimate expression of performance, combining a screaming V12 with a KERS hybrid system for instant response.",
    images: [
      "https://www.kimballstock.com/pix/car/p/06/aut-50-rk0860-01p.jpg",
      "https://www.kimballstock.com/pix/car/p/06/aut-50-rk0864-01p.jpg",
      "https://www.netcarshow.com/Ferrari-LaFerrari-2014-Side_Profile.9e071781.jpg"
    ],
  },
  {
    id: 24,
    name: "McLaren P1",
    brand: "McLaren",
    maker: "McLaren Automotive",
    country: "United Kingdom",
    price: "$1,150,000",
    speed: "350 km/h",
    hp: "903 hp",
    zeroTo100Mph: "4.7 s",
    weight: "1,547 kg",
    vehicleType: "Hybrid",
    description: "A hybrid hypercar known for its aggressive power delivery and striking, aerodynamic shrink-wrapped design.",
    images: [
      "https://www.kimballstock.com/pix/car/p/04/aut-28-rk0201-01p.jpg",
      "https://www.kimballstock.com/pix/car/p/04/aut-28-rk0203-01p.jpg",
      "https://www.netcarshow.com/McLaren-P1_Concept-2012-Side_Profile.64893dd9.jpg"
    ],
  },
  {
    id: 25,
    name: "Lamborghini Sián FKP 37",
    brand: "Lamborghini",
    maker: "Automobili Lamborghini S.p.A.",
    country: "Italy",
    price: "$3,600,000",
    speed: "350 km/h",
    hp: "808 hp",
    zeroTo100Mph: "5.8 s",
    weight: "1,595 kg",
    vehicleType: "Hybrid",
    description: "Lamborghini's first hybrid, utilizing supercapacitors instead of standard batteries to assist its mighty V12.",
    images: [
      "https://4kwallpapers.com/images/walls/thumbs_3t/14478.jpg",
      "https://i.ytimg.com/vi/2X5wQ1K4Hv4/maxresdefault.jpg",
      "https://audiclubna.org/wp-content/uploads/2025/03/2021_lamborghini_sian-fkp-37_T7__9315-67406-scaled.jpg.webp"
    ],
  },
  {
    id: 26,
    name: "Aston Martin Valkyrie",
    brand: "Aston Martin",
    maker: "Aston Martin Lagonda",
    country: "United Kingdom",
    price: "$3,000,000",
    speed: "400 km/h",
    hp: "1140 hp",
    zeroTo100Mph: "5.0 s",
    weight: "1,270 kg",
    vehicleType: "Combustion",
    description: "An F1 car for the road designed by Adrian Newey, featuring extreme underbody aerodynamics and a Cosworth V12.",
    images: [
      "https://www.topgear.com/sites/default/files/2023/03/4-Aston-Martin-Valkyrie.jpg",
      "https://media.astonmartin.com/wp-content/uploads/2024/10/85ea0b421d020274c7e9fe3d279a7566-m.jpg.webp",
      "https://media.astonmartin.com/wp-content/uploads/2024/10/ac67fcdd09fb7712c5cab5df037dae58-m.jpg.webp"
    ],
  },
  {
    id: 27,
    name: "BMW M4 CSL",
    brand: "BMW",
    maker: "BMW M GmbH",
    country: "Germany",
    price: "$140,000",
    speed: "307 km/h",
    hp: "543 hp",
    zeroTo100Mph: "8.1 s",
    weight: "1,625 kg",
    vehicleType: "Combustion",
    description: "A stripped-down, lightweight track special that represents the absolute peak of BMW's M4 performance capabilities.",
    images: [
      "https://mediapool.bmwgroup.com/download/edown/pressclub/publicq?dokNo=P90463173&attachment=1&actEvent=image",
      "https://www.autospies.com/images/users/Agent009/images/BMW%20M4%20CSL_Studio%20(7).jpg",
      "https://www.topgear.com/sites/default/files/2022/05/BMW_AK_M4_CSL_Seite.jpeg"
    ],
  },
  {
    id: 28,
    name: "BMW i8",
    brand: "BMW",
    maker: "BMW AG",
    country: "Germany",
    price: "$147,000",
    speed: "250 km/h",
    hp: "369 hp",
    zeroTo100Mph: "9.8 s",
    weight: "1,535 kg",
    vehicleType: "Hybrid",
    description: "A futuristic plug-in hybrid sports car featuring dramatic butterfly doors and an incredibly efficient carbon-fiber tub.",
    images: [
      "https://www.kimballstock.com/pix/car/p/01/aut-09-rk1291-01p.jpg",
      "https://w0.peakpx.com/wallpaper/471/798/HD-wallpaper-bmw-i8-bmw-car-blue-sportscar-supercar-rear-view.jpg",
      "https://static01.nyt.com/images/2014/05/11/automobiles/autoreviews/11bmw-i8-slides-slide-XKG5/11bmw-i8-slides-slide-XKG5-superJumbo.jpg"
    ],
  },
  {
    id: 29,
    name: "Pagani Zonda R",
    brand: "Pagani",
    maker: "Pagani Automobili S.p.A.",
    country: "Italy",
    price: "$2,800,000",
    speed: "350 km/h",
    hp: "740 hp",
    zeroTo100Mph: "6.0 s",
    weight: "1,070 kg",
    vehicleType: "Combustion",
    description: "A track-only, carbon-titanium masterpiece built entirely without racing restrictions, known for its deafening V12 exhaust note.",
    images: [
      "https://www.kimballstock.com/pix/car/p/05/aut-44-bk0008-01p.jpg",
      "https://www.topgear.com/sites/default/files/news/image/2015/04/Large%20Image_6751.jpg",
      "https://w0.peakpx.com/wallpaper/436/970/HD-wallpaper-pagani-zonda-r-side-car.jpg"
    ],
  },
  {
    id: 30,
    name: "Koenigsegg Agera RS",
    brand: "Koenigsegg",
    maker: "Koenigsegg Automotive AB",
    country: "Sweden",
    price: "$2,500,000",
    speed: "447 km/h",
    hp: "1160 hp",
    zeroTo100Mph: "5.5 s",
    weight: "1,395 kg",
    vehicleType: "Combustion",
    description: "The car that officially claimed the world's fastest production car title in 2017 on a closed highway in Nevada.",
    images: [
      "https://w0.peakpx.com/wallpaper/895/215/HD-wallpaper-koenigsegg-agera-rs1-2019-hypercar-front-view-white-sports-coupe-supercar-tuning-agera-white-agera-rs1-koenigsegg.jpg",
      "https://c8.alamy.com/comp/P6J377/19-may-2018-london-england-close-up-detail-of-an-supercar-koenigsegg-agera-r-elegant-brake-light-in-london-motor-show-P6J377.jpg",
      "https://w0.peakpx.com/wallpaper/32/591/HD-wallpaper-2017-koenigsegg-agera-rs-final-one-of-1-side-car.jpg"
    ],
  },
  {
    id: 31,
    name: "Hennessey Venom F5",
    brand: "Hennessey",
    maker: "Hennessey Special Vehicles",
    country: "USA",
    price: "$2,100,000",
    speed: "435 km/h",
    hp: "1817 hp",
    zeroTo100Mph: "4.7 s",
    weight: "1,385 kg",
    vehicleType: "Combustion",
    description: "An American hypercar built from the ground up to achieve one goal: absolute top speed dominance.",
    images: [
      "https://www.kimballstock.com/pix/car/p/06/aut-54-rk0001-01p.jpg",
      "https://www.hennesseymedia.com/wp-content/uploads/2025/08/Hennessey-Unveils-1-of-1-Manual-Venom-F5-with-2031-HP-Low-4.jpg",
      "https://www.hennesseymedia.com/wp-content/uploads/2025/03/Hennessey-Venom-F5-Configurator-Clash-High-3.jpg"
    ],
  },
  {
    id: 32,
    name: "SSC Tuatara",
    brand: "SSC",
    maker: "SSC North America",
    country: "USA",
    price: "$1,900,000",
    speed: "455 km/h",
    hp: "1750 hp",
    zeroTo100Mph: "5.4 s",
    weight: "1,247 kg",
    vehicleType: "Combustion",
    description: "An incredibly aerodynamic American hypercar engineered specifically to push the boundaries of straight-line speed records.",
    images: [
      "https://cdn.motor1.com/images/mgl/LBV8L/s1/2020-scc-tuatara.jpg",
      "https://cdn.motor1.com/images/mgl/EMq0o/s3/2020-scc-tuatara.jpg",
      "https://cdn.motor1.com/images/mgl/yKeX7/s1/2020-scc-tuatara.jpg"
    ],
  },
  {
    id: 33,
    name: "Rimac Nevera",
    brand: "Rimac",
    maker: "Rimac Automobili",
    country: "Croatia",
    price: "$2,200,000",
    speed: "412 km/h",
    hp: "1914 hp",
    zeroTo100Mph: "4.3 s",
    weight: "2,150 kg",
    vehicleType: "Full Electric",
    description: "An all-electric hypercar that has completely rewritten the rulebook on acceleration, quarter-mile times, and EV performance.",
    images: [
      "https://cdn.motor1.com/images/mgl/7ZQl81/s1/rimac-nevera-15th-anniversary-edition-front-3-4.jpg",
      "https://hips.hearstapps.com/hmg-prod/images/rimac-nevera-r-113-66be2b36ab91a.jpg?crop=0.611xw:0.916xh;0.196xw,0.0240xh&resize=1200:*",
      "https://assets.rimac-newsroom.com/1723561686-nevera_r_press_scketch_facundo_elias.jpg"
    ],
  },
  {
    id: 34,
    name: "Lotus Evija",
    brand: "Lotus",
    maker: "Lotus Cars",
    country: "United Kingdom",
    price: "$2,300,000",
    speed: "320 km/h",
    hp: "2000 hp",
    zeroTo100Mph: "6.0 s",
    weight: "1,680 kg",
    vehicleType: "Full Electric",
    description: "A striking, fully electric hypercar featuring massive venturi tunnels through the bodywork to generate extreme downforce.",
    images: [
      "https://media.gq-magazine.co.uk/photos/5d776fec60bd0400088c1eb8/16:9/w_2560%2Cc_limit/20190910-Lotus-04.jpg",
      "https://realtimeuk.com/wp-content/uploads/2022/06/lotus_evija_big_sur_config_movie_showreel_launch_0620-scaled.jpg",
      "https://hips.hearstapps.com/hmg-prod/images/2025-lotus-evija-124-6878019b99101.jpg?crop=0.821xw:0.617xh;0.179xw,0.186xh&resize=1200:*"
    ],
  },
  {
    id: 35,
    name: "Ferrari SF90 Stradale",
    brand: "Ferrari",
    maker: "Ferrari S.p.A.",
    country: "Italy",
    price: "$500,000",
    speed: "340 km/h",
    hp: "986 hp",
    zeroTo100Mph: "4.7 s",
    weight: "1,570 kg",
    vehicleType: "Hybrid",
    description: "Ferrari's first plug-in hybrid production car, utilizing three electric motors and a V8 to achieve near-hypercar performance.",
    images: [
      "https://www.kimballstock.com/pix/car/p/06/frr-04-rk0769-01p.jpg",
      "https://media.gettyimages.com/id/1713180684/photo/ferrari-sf90-sports-car-rear-lights-detail.jpg?s=1024x1024&w=gi&k=20&c=g95UgcD4X_Y01tUZHNurd7eMlXtv2G2yZYvFsbWEG0A=",
      "https://media.whichcar.com.au/uploads/2025/02/e1202921-ferrari-sf90-stradale-2019-547136.jpg"
    ],
  },
  {
    id: 36,
    name: "Lamborghini Revuelto",
    brand: "Lamborghini",
    maker: "Automobili Lamborghini S.p.A.",
    country: "Italy",
    price: "$600,000",
    speed: "350 km/h",
    hp: "1001 hp",
    zeroTo100Mph: "4.8 s",
    weight: "1,772 kg",
    vehicleType: "Hybrid",
    description: "The successor to the Aventador, maintaining the legendary V12 but pairing it with a cutting-edge plug-in hybrid system.",
    images: [
      "https://hips.hearstapps.com/hmg-prod/images/2024-lamborghini-revuelto-122-641a1d50c5283.jpg",
      "https://static0.hotcarsimages.com/wordpress/wp-content/uploads/2023/03/lamborghini-revuelto-rear-quarter-view-studio.jpg?q=50&fit=crop&w=825&dpr=1.5",
      "https://media.autoexpress.co.uk/image/private/s--NkcOopni--/f_auto,t_content-image-full-mobile@1/v1680081685/autoexpress/2023/03/Lamborghini%20Revuelto%202023-3.jpg"
    ],
  },
  {
    id: 37,
    name: "Mercedes-Benz SLS AMG",
    brand: "Mercedes-Benz",
    maker: "Mercedes-AMG GmbH",
    country: "Germany",
    price: "$200,000",
    speed: "315 km/h",
    hp: "583 hp",
    zeroTo100Mph: "7.2 s",
    weight: "1,620 kg",
    vehicleType: "Combustion",
    description: "A modern homage to the classic 300SL, featuring iconic gullwing doors and a naturally aspirated 6.2L V8.",
    images: [
      "https://www.netcarshow.com/Mercedes-Benz-SLS_AMG_Black_Series-2014-wallpaper.jpg",
      "https://w0.peakpx.com/wallpaper/149/132/HD-wallpaper-mercedes-benz-sls-amg-silver-sports-coupe-supercar-rear-view-tuning-sls-silver-sls-german-sports-cars-mercedes-thumbnail.jpg",
      "https://www.netcarshow.com/Mercedes-Benz-SLS_AMG_Black_Series-2014-Side_Profile.c75a767d.jpg"
    ],
  },
  {
    id: 38,
    name: "Porsche Carrera GT",
    brand: "Porsche",
    maker: "Porsche AG",
    country: "Germany",
    price: "$440,000",
    speed: "330 km/h",
    hp: "605 hp",
    zeroTo100Mph: "6.8 s",
    weight: "1,380 kg",
    vehicleType: "Vintage",
    description: "An analog masterpiece featuring a V10 engine originally developed for Le Mans and a notoriously tricky manual transmission.",
    images: [
      "https://static0.carbuzzimages.com/wordpress/wp-content/uploads/2025/02/2005-porsche-carrera-gt-exterior-front-view-at-rm-sothebys.jpg",
      "https://c8.alamy.com/comp/ADTD5E/porsche-carrera-gt-rear-view-ADTD5E.jpg",
      "https://www.stuttcars.com/wp-content/uploads/2021/07/227226_Side_Profile_Web.jpeg"
    ],
  },
  {
    id: 39,
    name: "McLaren Artura",
    brand: "McLaren",
    maker: "McLaren Automotive",
    country: "United Kingdom",
    price: "$233,000",
    speed: "330 km/h",
    hp: "671 hp",
    zeroTo100Mph: "6.9 s",
    weight: "1,498 kg",
    vehicleType: "Hybrid",
    description: "McLaren's next-generation hybrid supercar, combining a twin-turbo V6 with an electric motor for seamless power delivery.",
    images: [
      "https://smart-motoring.com/wp-content/uploads/2026/02/mclaren-artura-mcl39-3-4-front-studio.webp",
      "https://smart-motoring.com/wp-content/uploads/2026/02/mclaren-artura-mcl39-rear-3-4-1024x576.webp",
      "https://website-images.mclaren.com/5305/mclaren-artura-mcl39.jpg"
    ],
  },
  {
    id: 40,
    name: "BMW M1",
    brand: "BMW",
    maker: "BMW Motorsport GmbH",
    country: "Germany",
    price: "$500,000",
    speed: "262 km/h",
    hp: "273 hp",
    zeroTo100Mph: "14.0 s",
    weight: "1,300 kg",
    vehicleType: "Vintage",
    description: "BMW's original mid-engine supercar from the late 1970s, designed by Giugiaro and built for homologation racing.",
    images: [
      "https://media.gq-magazine.co.uk/photos/5d13aa559fa601dcdf839c19/16:9/w_2560%2Cc_limit/gq_bmw_m1_004.jpg",
      "https://static0.carbuzzimages.com/wordpress/wp-content/uploads/2025/07/1978-bmw-m1-2.jpg",
      "https://www.bmw-m.com/content/dam/bmw/marketBMW_M/www_bmw-m_com/topics/magazine-article-pool/2018/bmw-m1-portraet/bmw-m1-gallery-2.jpg"
    ],
  },
];

const CAR_IMAGE_FALLBACK = `data:image/svg+xml,${encodeURIComponent(
  '<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="675" viewBox="0 0 1200 675"><rect width="1200" height="675" fill="#111827"/><circle cx="600" cy="337.5" r="110" fill="#eab308"/><path d="M540 355h120l-22 36h-76z" fill="#111827"/></svg>'
)}`;

function normalizeImageUrl(url) {
  if (typeof url !== "string") return "";
  const trimmed = url.trim();
  if (!trimmed) return "";
  if (trimmed.startsWith("http://")) {
    return `https://${trimmed.slice(7)}`;
  }
  return trimmed;
}

for (const car of cars) {
  const normalizedImages = Array.isArray(car.images)
    ? car.images.map(normalizeImageUrl).filter(Boolean)
    : [];

  car.images = normalizedImages;
  car.image = normalizeImageUrl(car.image) || normalizedImages[0] || CAR_IMAGE_FALLBACK;
}

function getCarById(id){
  return cars.find(car => car.id === id);
}

window.cars = cars;
window.getCarById = getCarById;
window.CAR_IMAGE_FALLBACK = CAR_IMAGE_FALLBACK;
