// js/cars.js
const cars = [
  {
    id: 1,
    name: "Lamborghini Aventador",
    brand: "Lamborghini",
    maker: "Automobili Lamborghini S.p.A.",
    country: "Italy",
    price: "$500,000",
    speed: "350 km/h",
    hp: "770 hp",
    description:
      "A flagship V12 supercar famous for its aggressive, stealth-fighter styling and iconic scissor doors.",
    image: "assets/images/aventador.jpg",
  },
  {
    id: 2,
    name: "Ferrari 488",
    brand: "Ferrari",
    maker: "Ferrari S.p.A.",
    country: "Italy",
    price: "$280,000",
    speed: "330 km/h",
    hp: "661 hp",
    description:
      "An incredibly responsive mid-engine V8 supercar that delivers blistering track performance and daily usability.",
    image: "assets/images/ferrari488.jpg",
  },
  {
    id: 3,
    name: "McLaren 720S",
    brand: "McLaren",
    maker: "McLaren Automotive",
    country: "United Kingdom",
    price: "$300,000",
    speed: "341 km/h",
    hp: "710 hp",
    description:
      "A lightweight, aerodynamically advanced supercar offering mind-bending acceleration and a high-tech carbon fiber chassis.",
    image: "assets/images/mclaren720s.jpg",
  },
  {
    id: 4,
    name: "Bugatti Chiron",
    brand: "Bugatti",
    maker: "Bugatti Automobiles S.A.S.",
    country: "France",
    price: "$3,000,000",
    speed: "420 km/h",
    hp: "1500 hp",
    description:
      "An ultra-luxury hypercar powered by a quad-turbo W16 engine, renowned for its record-breaking top speeds.",
    image: "assets/images/chiron.jpg",
  },
  {
    id: 5,
    name: "Porsche 911 Turbo S",
    brand: "Porsche",
    maker: "Porsche AG",
    country: "Germany",
    price: "$230,000",
    speed: "330 km/h",
    hp: "640 hp",
    description:
      "The ultimate everyday supercar, combining all-wheel-drive traction with explosive twin-turbo flat-six power.",
    image: "assets/images/911turbos.jpg",
  },
  {
    id: 6,
    name: "Audi R8 V10 Plus",
    brand: "Audi",
    maker: "Audi Sport GmbH",
    country: "Germany",
    price: "$200,000",
    speed: "330 km/h",
    hp: "602 hp",
    description:
      "A refined, naturally aspirated V10 supercar sharing its core DNA with the Lamborghini Huracán.",
    image: "assets/images/r8v10.jpg",
  },
  {
    id: 7,
    name: "Mercedes-AMG GT Black Series",
    brand: "Mercedes-Benz",
    maker: "Mercedes-AMG GmbH",
    country: "Germany",
    price: "$325,000",
    speed: "325 km/h",
    hp: "720 hp",
    description:
      "A track-focused monster featuring a flat-plane crank V8 and extreme aerodynamics derived from GT3 racing.",
    image: "assets/images/amggt_black.jpg",
  },
  {
    id: 8,
    name: "BMW M8 Competition",
    brand: "BMW",
    maker: "BMW M GmbH",
    country: "Germany",
    price: "$130,000",
    speed: "305 km/h",
    hp: "617 hp",
    description:
      "A heavily muscular grand tourer that crosses into supercar territory with its ferocious twin-turbo V8 and all-wheel drive.",
    image: "assets/images/m8competition.jpg",
  },
  {
    id: 9,
    name: "Aston Martin DBS Superleggera",
    brand: "Aston Martin",
    maker: "Aston Martin Lagonda",
    country: "United Kingdom",
    price: "$316,000",
    speed: "340 km/h",
    hp: "715 hp",
    description:
      "A stunningly beautiful V12 grand tourer offering massive torque and classic British elegance.",
    image: "assets/images/dbs.jpg",
  },
  {
    id: 10,
    name: "Pagani Huayra",
    brand: "Pagani",
    maker: "Pagani Automobili S.p.A.",
    country: "Italy",
    price: "$2,600,000",
    speed: "383 km/h",
    hp: "730 hp",
    description:
      "A rolling piece of art featuring active aerodynamics and a bespoke AMG-sourced twin-turbo V12.",
    image: "assets/images/huayra.jpg",
  },
  {
    id: 11,
    name: "Koenigsegg Jesko",
    brand: "Koenigsegg",
    maker: "Koenigsegg Automotive AB",
    country: "Sweden",
    price: "$3,000,000",
    speed: "480 km/h",
    hp: "1600 hp",
    description:
      "A track-oriented megacar engineered to break the 300 mph barrier, featuring a revolutionary 9-speed 'Light Speed Transmission'.",
    image: "assets/images/jesko.jpg",
  },
  {
    id: 12,
    name: "Ford GT",
    brand: "Ford",
    maker: "Ford Motor Company / Multimatic",
    country: "USA / Canada",
    price: "$500,000",
    speed: "347 km/h",
    hp: "660 hp",
    description:
      "A Le Mans-winning race car for the road, built almost entirely of carbon fiber with a potent EcoBoost V6.",
    image: "assets/images/fordgt.jpg",
  },
  {
    id: 13,
    name: "Chevrolet Corvette Z06",
    brand: "Chevrolet",
    maker: "General Motors",
    country: "USA",
    price: "$110,000",
    speed: "313 km/h",
    hp: "670 hp",
    description:
      "An American supercar disruptor packing a high-revving, flat-plane crank naturally aspirated V8.",
    image: "assets/images/corvettez06.jpg",
  },
  {
    id: 14,
    name: "Nissan GT-R Nismo",
    brand: "Nissan",
    maker: "Nissan Motor Co., Ltd.",
    country: "Japan",
    price: "$210,000",
    speed: "330 km/h",
    hp: "600 hp",
    description:
      "The pinnacle of the 'Godzilla' lineage, featuring GT3 race-derived turbochargers and carbon fiber bodywork.",
    image: "assets/images/gtrnismo.jpg",
  },
  {
    id: 15,
    name: "Acura NSX Type S",
    brand: "Acura",
    maker: "Honda Motor Company",
    country: "USA (Assembled)",
    price: "$170,000",
    speed: "307 km/h",
    hp: "600 hp",
    description:
      "A highly advanced hybrid supercar utilizing three electric motors and a twin-turbo V6 for precise torque vectoring.",
    image: "assets/images/nsx.jpg",
  },
  {
    id: 16,
    name: "Lexus LFA",
    brand: "Lexus",
    maker: "Toyota Motor Corporation",
    country: "Japan",
    price: "$375,000",
    speed: "325 km/h",
    hp: "552 hp",
    description:
      "A legendary, limited-production supercar famous for having one of the best-sounding V10 engines in automotive history.",
    image: "assets/images/lfa.jpg",
  },
  {
    id: 17,
    name: "Maserati MC20",
    brand: "Maserati",
    maker: "Maserati S.p.A.",
    country: "Italy",
    price: "$210,000",
    speed: "325 km/h",
    hp: "621 hp",
    description:
      "Maserati’s return to mid-engine supercars, powered by the innovative twin-spark 'Nettuno' V6 engine.",
    image: "assets/images/mc20.jpg",
  },
  {
    id: 18,
    name: "Ferrari F8 Tributo",
    brand: "Ferrari",
    maker: "Ferrari S.p.A.",
    country: "Italy",
    price: "$280,000",
    speed: "340 km/h",
    hp: "710 hp",
    description:
      "A tribute to Ferrari's most powerful V8 engine, wrapping staggering performance in beautiful, aerodynamic bodywork.",
    image: "assets/images/f8tributo.jpg",
  },
  {
    id: 19,
    name: "Lamborghini Huracán Performante",
    brand: "Lamborghini",
    maker: "Automobili Lamborghini S.p.A.",
    country: "Italy",
    price: "$275,000",
    speed: "325 km/h",
    hp: "631 hp",
    description:
      "A track-focused variant of the Huracán featuring the innovative 'ALA' active aerodynamics system.",
    image: "assets/images/huracan.jpg",
  },
  {
    id: 20,
    name: "McLaren Senna",
    brand: "McLaren",
    maker: "McLaren Automotive",
    country: "United Kingdom",
    price: "$1,000,000",
    speed: "335 km/h",
    hp: "789 hp",
    description:
      "An unapologetic track car designed solely to set lap records, prioritizing downforce and weight reduction above all else.",
    image: "assets/images/senna.jpg",
  },
  {
    id: 21,
    name: "Bugatti Veyron Super Sport",
    brand: "Bugatti",
    maker: "Bugatti Automobiles S.A.S.",
    country: "France",
    price: "$2,500,000",
    speed: "431 km/h",
    hp: "1200 hp",
    description:
      "The hypercar that defined an era, holding the production car top speed record for years with its massive W16 engine.",
    image: "assets/images/veyron.jpg",
  },
  {
    id: 22,
    name: "Porsche 918 Spyder",
    brand: "Porsche",
    maker: "Porsche AG",
    country: "Germany",
    price: "$845,000",
    speed: "345 km/h",
    hp: "887 hp",
    description:
      "A member of the 'Holy Trinity', this hybrid hypercar proved that electrification could push track performance to new limits.",
    image: "assets/images/918spyder.jpg",
  },
  {
    id: 23,
    name: "Ferrari LaFerrari",
    brand: "Ferrari",
    maker: "Ferrari S.p.A.",
    country: "Italy",
    price: "$1,400,000",
    speed: "350 km/h",
    hp: "950 hp",
    description:
      "Ferrari's ultimate expression of performance, combining a screaming V12 with a KERS hybrid system for instant response.",
    image: "assets/images/laferrari.jpg",
  },
  {
    id: 24,
    name: "McLaren P1",
    brand: "McLaren",
    maker: "McLaren Automotive",
    country: "United Kingdom",
    price: "$1,150,000",
    speed: "350 km/h",
    hp: "903 hp",
    description:
      "A hybrid hypercar known for its aggressive power delivery and striking, aerodynamic shrink-wrapped design.",
    image: "assets/images/p1.jpg",
  },
  {
    id: 25,
    name: "Lamborghini Sián FKP 37",
    brand: "Lamborghini",
    maker: "Automobili Lamborghini S.p.A.",
    country: "Italy",
    price: "$3,600,000",
    speed: "350 km/h",
    hp: "808 hp",
    description:
      "Lamborghini's first hybrid, utilizing supercapacitors instead of standard batteries to assist its mighty V12.",
    image: "assets/images/sian.jpg",
  },
  {
    id: 26,
    name: "Aston Martin Valkyrie",
    brand: "Aston Martin",
    maker: "Aston Martin Lagonda",
    country: "United Kingdom",
    price: "$3,000,000",
    speed: "400 km/h",
    hp: "1140 hp",
    description:
      "An F1 car for the road designed by Adrian Newey, featuring extreme underbody aerodynamics and a Cosworth V12.",
    image: "assets/images/valkyrie.jpg",
  },
  {
    id: 27,
    name: "BMW M4 CSL",
    brand: "BMW",
    maker: "BMW M GmbH",
    country: "Germany",
    price: "$140,000",
    speed: "307 km/h",
    hp: "543 hp",
    description:
      "A stripped-down, lightweight track special that represents the absolute peak of BMW's M4 performance capabilities.",
    image: "assets/images/m4csl.jpg",
  },
  {
    id: 28,
    name: "BMW i8",
    brand: "BMW",
    maker: "BMW AG",
    country: "Germany",
    price: "$147,000",
    speed: "250 km/h",
    hp: "369 hp",
    description:
      "A futuristic plug-in hybrid sports car featuring dramatic butterfly doors and an incredibly efficient carbon-fiber tub.",
    image: "assets/images/bmwi8.jpg",
  },
  {
    id: 29,
    name: "Pagani Zonda R",
    brand: "Pagani",
    maker: "Pagani Automobili S.p.A.",
    country: "Italy",
    price: "$2,800,000",
    speed: "350 km/h",
    hp: "740 hp",
    description:
      "A track-only, carbon-titanium masterpiece built entirely without racing restrictions, known for its deafening V12 exhaust note.",
    image: "assets/images/zondar.jpg",
  },
  {
    id: 30,
    name: "Koenigsegg Agera RS",
    brand: "Koenigsegg",
    maker: "Koenigsegg Automotive AB",
    country: "Sweden",
    price: "$2,500,000",
    speed: "447 km/h",
    hp: "1160 hp",
    description:
      "The car that officially claimed the world's fastest production car title in 2017 on a closed highway in Nevada.",
    image: "assets/images/agerars.jpg",
  },
  {
    id: 31,
    name: "Hennessey Venom F5",
    brand: "Hennessey",
    maker: "Hennessey Special Vehicles",
    country: "USA",
    price: "$2,100,000",
    speed: "435 km/h",
    hp: "1817 hp",
    description:
      "An American hypercar built from the ground up to achieve one goal: absolute top speed dominance.",
    image: "assets/images/venomf5.jpg",
  },
  {
    id: 32,
    name: "SSC Tuatara",
    brand: "SSC",
    maker: "SSC North America",
    country: "USA",
    price: "$1,900,000",
    speed: "455 km/h",
    hp: "1750 hp",
    description:
      "An incredibly aerodynamic American hypercar engineered specifically to push the boundaries of straight-line speed records.",
    image: "assets/images/tuatara.jpg",
  },
  {
    id: 33,
    name: "Rimac Nevera",
    brand: "Rimac",
    maker: "Rimac Automobili",
    country: "Croatia",
    price: "$2,200,000",
    speed: "412 km/h",
    hp: "1914 hp",
    description:
      "An all-electric hypercar that has completely rewritten the rulebook on acceleration, quarter-mile times, and EV performance.",
    image: "assets/images/nevera.jpg",
  },
  {
    id: 34,
    name: "Lotus Evija",
    brand: "Lotus",
    maker: "Lotus Cars",
    country: "United Kingdom",
    price: "$2,300,000",
    speed: "320 km/h",
    hp: "2000 hp",
    description:
      "A striking, fully electric hypercar featuring massive venturi tunnels through the bodywork to generate extreme downforce.",
    image: "assets/images/evija.jpg",
  },
  {
    id: 35,
    name: "Ferrari SF90 Stradale",
    brand: "Ferrari",
    maker: "Ferrari S.p.A.",
    country: "Italy",
    price: "$500,000",
    speed: "340 km/h",
    hp: "986 hp",
    description:
      "Ferrari's first plug-in hybrid production car, utilizing three electric motors and a V8 to achieve near-hypercar performance.",
    image: "assets/images/sf90.jpg",
  },
  {
    id: 36,
    name: "Lamborghini Revuelto",
    brand: "Lamborghini",
    maker: "Automobili Lamborghini S.p.A.",
    country: "Italy",
    price: "$600,000",
    speed: "350 km/h",
    hp: "1001 hp",
    description:
      "The successor to the Aventador, maintaining the legendary V12 but pairing it with a cutting-edge plug-in hybrid system.",
    image: "assets/images/revuelto.jpg",
  },
  {
    id: 37,
    name: "Mercedes-Benz SLS AMG",
    brand: "Mercedes-Benz",
    maker: "Mercedes-AMG GmbH",
    country: "Germany",
    price: "$200,000",
    speed: "315 km/h",
    hp: "583 hp",
    description:
      "A modern homage to the classic 300SL, featuring iconic gullwing doors and a naturally aspirated 6.2L V8.",
    image: "assets/images/slsamg.jpg",
  },
  {
    id: 38,
    name: "Porsche Carrera GT",
    brand: "Porsche",
    maker: "Porsche AG",
    country: "Germany",
    price: "$440,000",
    speed: "330 km/h",
    hp: "605 hp",
    description:
      "An analog masterpiece featuring a V10 engine originally developed for Le Mans and a notoriously tricky manual transmission.",
    image: "assets/images/carreragt.jpg",
  },
  {
    id: 39,
    name: "McLaren Artura",
    brand: "McLaren",
    maker: "McLaren Automotive",
    country: "United Kingdom",
    price: "$233,000",
    speed: "330 km/h",
    hp: "671 hp",
    description:
      "McLaren's next-generation hybrid supercar, combining a twin-turbo V6 with an electric motor for seamless power delivery.",
    image: "assets/images/artura.jpg",
  },
  {
    id: 40,
    name: "BMW M1",
    brand: "BMW",
    maker: "BMW Motorsport GmbH",
    country: "Germany",
    price: "$500,000",
    speed: "262 km/h",
    hp: "273 hp",
    description:
      "BMW's original mid-engine supercar from the late 1970s, designed by Giugiaro and built for homologation racing.",
    image: "assets/images/bmwm1.jpg",
  },
];
