const fs = require("fs");
const path = require("path");

const rootDir = path.resolve(__dirname, "..");
const envPath = path.join(rootDir, ".env");
const envLocalPath = path.join(rootDir, ".env.local");
const outputPath = path.join(rootDir, "env.js");

const REQUIRED_KEYS = [
  "FIREBASE_API_KEY",
  "FIREBASE_AUTH_DOMAIN",
  "FIREBASE_PROJECT_ID",
  "FIREBASE_STORAGE_BUCKET",
  "FIREBASE_MESSAGING_SENDER_ID",
  "FIREBASE_APP_ID",
];

function stripWrappingQuotes(value) {
  if (!value) return value;
  if (
    (value.startsWith('"') && value.endsWith('"')) ||
    (value.startsWith("'") && value.endsWith("'"))
  ) {
    return value.slice(1, -1);
  }
  return value;
}

function parseEnv(content) {
  const result = {};

  for (const line of content.split(/\r?\n/)) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;

    const equalsAt = trimmed.indexOf("=");
    if (equalsAt === -1) continue;

    const key = trimmed.slice(0, equalsAt).trim();
    const value = stripWrappingQuotes(trimmed.slice(equalsAt + 1).trim());
    if (!key) continue;

    result[key] = value;
  }

  return result;
}

function readEnvFile(filePath) {
  if (!fs.existsSync(filePath)) return {};
  return parseEnv(fs.readFileSync(filePath, "utf8"));
}

function mergeEnv(...sources) {
  return Object.assign({}, ...sources);
}

function pickFirebaseVars(source) {
  const result = {};
  const keys = [
    ...REQUIRED_KEYS,
    "FIREBASE_ADMIN_EMAIL",
    "FIREBASE_EXPECTED_AUTH_DOMAINS",
  ];

  for (const key of keys) {
    const value = source[key];
    if (typeof value === "string" && value.trim()) {
      result[key] = value.trim();
    }
  }

  return result;
}

function writeEnvLocalFile(values) {
  const header = [
    "# Local Firebase configuration (generated by scripts/generate-env.js)",
    "# This file is ignored by git and safe for local development.",
    "# For Vercel, set the same keys in Project Settings > Environment Variables.",
    "",
  ];

  const body = Object.entries(values).map(([key, value]) => `${key}=${value}`);
  const text = [...header, ...body, ""].join("\n");

  fs.writeFileSync(envLocalPath, text, "utf8");
}

const envFromDotEnv = readEnvFile(envPath);
const envFromLocal = readEnvFile(envLocalPath);
const envFromProcess = pickFirebaseVars(process.env || {});
const mergedEnv = mergeEnv(envFromDotEnv, envFromLocal, envFromProcess);
const envVars = pickFirebaseVars(mergedEnv);

if (!fs.existsSync(envLocalPath)) {
  writeEnvLocalFile(envVars);
  console.log(`Generated ${path.relative(rootDir, envLocalPath)} with Firebase values.`);
} else {
  const localMissing = Object.keys(envVars).filter((key) => !envFromLocal[key]);
  if (localMissing.length > 0) {
    writeEnvLocalFile({ ...envVars, ...envFromLocal });
    console.log(`Updated ${path.relative(rootDir, envLocalPath)} with missing Firebase values.`);
  }
}

const missingKeys = REQUIRED_KEYS.filter((key) => !envVars[key]);
if (missingKeys.length > 0) {
  console.error(
    `Missing required Firebase key(s): ${missingKeys.join(", ")}. ` +
      "Set them in .env.local for local dev or in deployment environment variables."
  );
  process.exit(1);
}

const runtime = `window.__ENV = ${JSON.stringify(envVars, null, 2)};\n`;

fs.writeFileSync(outputPath, runtime, "utf8");
console.log(`Generated ${path.relative(rootDir, outputPath)} from Firebase environment variables.`);
